import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/Layout/NavBar/NavBar";
import Footer from "@/components/Layout/Footer/Footer";
import { getBootcamps } from "@/requests/getBootcamps";
import Clg from "@/utils/Clg";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = { children: React.ReactNode };
const RootLayout = async ({ children }: RootLayoutProps) => {
  ////////////////////////////////////////////////////////////
  const { bootcamps } = await getBootcamps();
  ////////////////////////////////////////////////////////////
  // delete bellow uncomment above
  ////////////////////////////////////////////////////////////
  // const bootcamps: bootcamp[] = [
  //   { url: "", logo: "", status: "", header_title: "bc1" },
  //   { url: "", logo: "", status: "", header_title: "bc2" },
  //   { url: "", logo: "", status: "", header_title: "bc3" },
  //   { url: "", logo: "", status: "", header_title: "bc4" },
  // ];
  ////////////////////////////////////////////////////////////
  return (
    <html dir="rtl" lang="en">
      <body className="flex overflow-x-hidden overflow-y-auto flex-col w-screen min-h-dvh bg-background font-vazir text-black">
        <NavBar bootcamps={bootcamps} />
        {children}
        <Footer />
      </body>
    </html>
  );
};
export default RootLayout;
