import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/Layout/NavBar/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = { children: React.ReactNode };
const RootLayout = async ({ children }: RootLayoutProps) => {
  const { bootcamps, courses } = await fetch(
    `${process.env.BASE_URL}/header/header_sections.php`,
    {
      method: "POST",
      body: JSON.stringify({
        API_KEY: process.env.API_KEY,
        Content_Type: process.env.Content_Type,
      }),
      cache: "no-store",
    }
  ).then((res) => res.json());
  return (
    <html lang="en">
      <body className="max-w-[1200px] px-5 w-full mx-auto bg-background font-vazir">
        <NavBar bootcamps={bootcamps}/>
        {children}
      </body>
    </html>
  );
};
export default RootLayout;
