import type { Metadata } from "next";
import Footer from "@/components/Layout/Footer/Footer";
import AuthModal from "@/components/Auth/AuthModal";
import NavBar from "@/components/Layout/NavBar/NavBar";
import { ReactNode } from "react";

export const metadata: Metadata = {
  //todo
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = { children: ReactNode };
const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <>
      <NavBar />
      {children}
      <Footer />
      <AuthModal />
    </>
  );
};
export default RootLayout;
